---
## This is needed for sshpass
- name: Install EPEL
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
    state: present

- name: Install base packages
  yum:
    name:
      - vim
      - git
      - wget
      - nano
      - tree
      - sshpass
      - tmux
      - python-pip
      - ansible
      - gcc
    state: present
  register: yum_check
  until: yum_check is not failed
  retries: 4
  delay: 5

- name: Install ansible.cfg and vimrc in home directory
  template:
    src: ansible.cfg.j2
    dest: "/home/{{ username }}/.ansible.cfg"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install vimrc in home directory
  template:
    src: vimrc.j2
    dest: "/home/{{ username }}/.vimrc"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Get latest release of Coder binary
  uri:
    url: https://api.github.com/repos/cdr/code-server/releases/latest
  register: github_result

- name: Save url for extraction of Coder binary
  set_fact:
    download_url: "{{item.browser_download_url}}"
    version_name: "{{item.name.split('.tar')[0]}}"
  when: "'linux' in item.browser_download_url"
  loop: "{{github_result.json.assets}}"
  loop_control:
    label: "{{ item.browser_download_url }}"

- name: Extract file
  unarchive:
    src: "{{download_url}}"
    dest: "/home/{{username}}"
    remote_src: true
  register: output

- name: Install ansible vscode extension
  command: "/home/{{username}}/{{ version_name }}/code-server --auth none --install-extension vscoss.vscode-ansible"
  register: result

- name: Move binary to /opt
  copy:
    src: /home/{{username}}/{{ version_name }}/code-server
    dest: /opt/code-server
    remote_src: true
    mode: '0744'
    owner: "{{username}}"
    group: "{{username}}"

- name: Apply systemd service file
  template:
    src: code-server.service.j2
    dest: /etc/systemd/system/code-server.service
    owner: "{{username}}"
    group: wheel
    mode: '0744'

- name: Start code-server service
  service:
    name: code-server
    state: started
    enabled: true

- name: Cleanup Coder binary from student directory
  file:
    path: /home/{{username}}/{{ version_name }}
    state: absent

- name: setup control node networking
  include_tasks: "networking.yml"
  when: workshop_type in ['networking', 'f5']

- name: setup control node security automation
  include_tasks: "security.yml"
  when: workshop_type == "security"

- name: RHEL mode - setup control node
  include_tasks: "rhel.yml"
  when: workshop_type == 'rhel'

- name: RHEL mode and copy rhel assets - copy to control node
  include_tasks: "copy_rhel_assets.yml"
  when: workshop_type == 'rhel' and copy_rhel_assets|bool == true

- name: Devops mode - setup control node
  include_tasks: "devops.yml"
  when: workshop_type == 'devops'

- name: Windows mode - setup control node
  include_tasks: "windows.yml"
  when: workshop_type == 'windows'

- name: check to see if ansible tower is already up and running
  uri:
    url: https://localhost/api/v2/ping/
    method: GET
    user: admin
    password: "{{admin_password}}"
    validate_certs: false
    force_basic_auth: true
  register: check_tower
  ignore_errors: true
  when:
    - towerinstall is defined
    - towerinstall|bool

- name: install tower if knob is set
  include_tasks: "tower.yml"
  when:
    - towerinstall is defined
    - towerinstall|bool
    - check_tower is failed

- name: Ensure eula is accepted if posting license
  lineinfile:
    path: "{{playbook_dir}}/tower_license.json"
    line: '    "eula_accepted": true,'
    insertbefore: '"company_name"'
    state: present
  delegate_to: localhost
  run_once: true
  become: false
  when:
    - autolicense is defined
    - autolicense|bool

- name: Post license key
  uri:
    url: https://{{ansible_host}}/api/v2/config/
    method: POST
    user: admin
    password: "{{admin_password}}"
    body: "{{ lookup('file',playbook_dir+'/tower_license.json') }}"
    body_format: json
    validate_certs: false
    force_basic_auth: true
  when:
    - autolicense is defined
    - autolicense|bool

- name: RHEL Mode - Create tower assets
  include_tasks: "create_rhel_tower_assets.yml"
  when: 
    - workshop_type == 'rhel'
    - copy_rhel_assets|bool == true
    - towerinstall is defined
    - towerinstall|bool
    - autolicense is defined
    - autolicense|bool

- name: INSTALL VSCODE AND XRDP
  include_tasks: gui.yml
  when: xrdp|bool
