---
- name: upgrade pip
  become: true
  pip:
    name: pip
    state: latest
# Force <45 because 45.0.0 dropped support for python2
# This is required for Juniper ncclient - do a pip show ncclient to see requirements
- name: upgrade setuptools to 44
  become: true
  pip:
    name: setuptools==44.0.0

- name: install additional packages (NETWORKING MODE)
  become: true
  pip:
    name:
      - netaddr
      - ncclient
    state: latest

- name: Move networking workshop folder to correct location  (NETWORKING MODE)
  copy:
    src: /tmp/workshops/exercises/ansible_network/
    dest: /home/{{ username }}/networking-workshop
    remote_src: true
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create lab inventory directory (NETWORKING MODE)
  file:
    state: directory
    path: /home/{{ username }}/networking-workshop/lab_inventory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Put student inventory in proper spot (NETWORKING MODE)
  copy:
    src: "{{ playbook_dir }}/{{ec2_name_prefix}}/{{ username }}-instances.txt"
    dest: "/home/{{ username }}/networking-workshop/lab_inventory/hosts"
    owner: "{{ username }}"
    group: "{{ username }}"
  when: username in inventory_hostname
